Revert "Replaced a deprecated method call."
This reverts commit 2ae0e13205255c6f62c1ca6b676ee0d8d5d7b293.

Was getting compile error:
/Users/agrieve/git/mca/mobile-chrome-apps/spec/platforms/android/src/org/chromium/ChromeIdentity.java:275: error: unreported exception GooglePlayServicesAvailabilityException; must be caught or declared to be thrown
            GoogleAuthUtil.clearToken(context, token);
                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/agrieve/git/mca/mobile-chrome-apps/spec/platforms/android/src/org/apache/cordova/file/ContentFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error